# Fonte
font_family      Cascadia Code NF
bold_font        Cascadia Code NF
italic_font      Cascadia Code NF
bold_italic_font Cascadia Code NF
font_size        11.0

# Cursor
cursor_shape beam
cursor_blink_interval 0
cursor_trail 3

# Scroll
scrollback_lines 10000

# Aparência
background_opacity 0.95
confirm_os_window_close 0

# Desempenho
sync_to_monitor yes

# Posição: top ou bottom
tab_bar_edge bottom

# Estilo: fade, slant, separator, powerline (como tmux), etc.
tab_bar_style powerline

# Alinhamento
tab_bar_align left

# Cor de fundo
tab_bar_background #292d3e

# Cor do texto ativo/inativo
active_tab_background #89b4fa
active_tab_foreground #1e1e2e
inactive_tab_background #313244
inactive_tab_foreground #cdd6f4

# Fonte e tamanho
tab_bar_font_family Cascadia Code NF
tab_bar_min_tabs 1



# BEGIN_KITTY_THEME
# Campbell
include current-theme.conf
# END_KITTY_THEME
